/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { InstallmentPlanController } from '../src';
import { testClient } from './testClient.js';
import { expectHeadersToMatch, makeApiCall } from './testHelper.js';

describe('InstallmentPlanController', () => {
  let controller : InstallmentPlanController;

  beforeAll(() => {
    controller = new InstallmentPlanController(testClient);
  });

  it('should Test InstallmentPlan_Search', async () => {
    const response = await makeApiCall(
      () => controller.installmentPlanSearch(
        undefined,
        undefined,
        undefined,
        undefined
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['text/plain', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test InstallmentPlan_Search1', async () => {
    const response = await makeApiCall(
      () => controller.installmentPlanSearch(
        undefined,
        undefined,
        undefined,
        undefined
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test InstallmentPlan_Search2', async () => {
    const response = await makeApiCall(
      () => controller.installmentPlanSearch(
        undefined,
        undefined,
        undefined,
        undefined
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['text/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
