/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Client, Configuration, Environment } from '../src';

export const testClient = new Client(createConfigurationFromEnvironment());

function createConfigurationFromEnvironment(): Partial<Configuration> {
  const config: Partial<Configuration> = {};

  const environment = process.env.SPLITIT_WEB_API_V_3_LIB_ENVIRONMENT;
  const timeout = process.env.SPLITIT_WEB_API_V_3_LIB_TIMEOUT;
  const oAuthClientId = process.env.SPLITIT_WEB_API_V_3_LIB_O_AUTH_CLIENT_ID;
  const oAuthClientSecret = process.env.SPLITIT_WEB_API_V_3_LIB_O_AUTH_CLIENT_SECRET;
  const oAuthClientId2 = process.env.SPLITIT_WEB_API_V_3_LIB_O_AUTH_CLIENT_ID_2;
  const oAuthClientSecret2 = process.env.SPLITIT_WEB_API_V_3_LIB_O_AUTH_CLIENT_SECRET_2;

  if (environment !== undefined) {
    config.environment = environment as Environment;
  }

  if (timeout !== undefined && timeout !== '') {
    config.timeout = parseInt(timeout);
  }

  if (oAuthClientId !== undefined && oAuthClientSecret !== undefined) {
    config.oAuth2SandboxCredentials = {
      oAuthClientId: oAuthClientId,
      oAuthClientSecret: oAuthClientSecret,
    };
  }

  if (oAuthClientId2 !== undefined && oAuthClientSecret2 !== undefined) {
    config.oAuth2ProductionCredentials = {
      oAuthClientId: oAuthClientId2,
      oAuthClientSecret: oAuthClientSecret2,
    };
  }

  return config;
}
