/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ErrorExtended } from '../models/errorExtended.js';

/**
 * Creates an instance of FailedResponse
 */
interface FailedResponse {
  TraceId?: string;
  Error?: ErrorExtended;
}

export class FailedResponseError extends ApiError<FailedResponse> {}
