/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ErrorExtended } from '../models/errorExtended.js';
import { PaymentInfo } from '../models/paymentInfo.js';

/**
 * Creates an instance of PlanErrorResponse
 */
interface PlanErrorResponse {
  TraceId?: string;
  Error?: ErrorExtended;
  InstallmentPlanNumber?: string;
  PaymentInfo?: PaymentInfo;
}

export class PlanErrorResponseError extends ApiError<PlanErrorResponse> {}
