/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CheckInstallmentsEligibilityRequest,
  checkInstallmentsEligibilityRequestSchema,
} from '../models/checkInstallmentsEligibilityRequest.js';
import {
  EligibilityTermsAndConditionResponse,
  eligibilityTermsAndConditionResponseSchema,
} from '../models/eligibilityTermsAndConditionResponse.js';
import {
  InitiatePlanResponse,
  initiatePlanResponseSchema,
} from '../models/initiatePlanResponse.js';
import {
  InstallmentPlanCreateRequest,
  installmentPlanCreateRequestSchema,
} from '../models/installmentPlanCreateRequest.js';
import {
  InstallmentPlanCreateResponse,
  installmentPlanCreateResponseSchema,
} from '../models/installmentPlanCreateResponse.js';
import {
  InstallmentPlanGetResponse,
  installmentPlanGetResponseSchema,
} from '../models/installmentPlanGetResponse.js';
import {
  InstallmentPlanInitiateRequest,
  installmentPlanInitiateRequestSchema,
} from '../models/installmentPlanInitiateRequest.js';
import {
  InstallmentPlanRefundRequest,
  installmentPlanRefundRequestSchema,
} from '../models/installmentPlanRefundRequest.js';
import {
  InstallmentPlanRefundResponse,
  installmentPlanRefundResponseSchema,
} from '../models/installmentPlanRefundResponse.js';
import {
  InstallmentPlanSearchResponse,
  installmentPlanSearchResponseSchema,
} from '../models/installmentPlanSearchResponse.js';
import {
  InstallmentPlanUpdateRequest,
  installmentPlanUpdateRequestSchema,
} from '../models/installmentPlanUpdateRequest.js';
import {
  InstallmentPlanUpdateRequestByIdentifier,
  installmentPlanUpdateRequestByIdentifierSchema,
} from '../models/installmentPlanUpdateRequestByIdentifier.js';
import {
  InstallmentPlanUpdateResponse,
  installmentPlanUpdateResponseSchema,
} from '../models/installmentPlanUpdateResponse.js';
import {
  InstallmentsEligibilityResponse,
  installmentsEligibilityResponseSchema,
} from '../models/installmentsEligibilityResponse.js';
import { TestModesEnum, testModesEnumSchema } from '../models/testModesEnum.js';
import {
  VerifyAuthorizationResponse,
  verifyAuthorizationResponseSchema,
} from '../models/verifyAuthorizationResponse.js';
import { nullable, optional, string, unknown } from '../schema.js';
import { BaseController } from './baseController.js';
import { FailedResponseError } from '../errors/failedResponseError.js';
import { PlanErrorResponseError } from '../errors/planErrorResponseError.js';

export class InstallmentPlanController extends BaseController {
  /**
   * @param installmentPlanNumber
   * @param xSplititTouchPoint    TouchPoint
   * @return Response from the API call
   */
  async installmentPlanGet(
    installmentPlanNumber: string,
    xSplititTouchPoint?: string | null,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InstallmentPlanGetResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      installmentPlanNumber: [installmentPlanNumber, string()],
      xSplititTouchPoint: [xSplititTouchPoint, optional(nullable(string()))],
    });
    req.header('X-Splitit-TouchPoint', mapped.xSplititTouchPoint);
    req.appendTemplatePath`/api/installmentplans/${mapped.installmentPlanNumber}`;
    req.throwOn(401, FailedResponseError, '');
    req.throwOn(403, FailedResponseError, '');
    req.throwOn(404, FailedResponseError, '');
    req.throwOn(500, FailedResponseError, '');
    req.authenticate([{ oAuth2Sandbox: true }, { oAuth2Production: true }]);
    return req.callAsJson(installmentPlanGetResponseSchema, requestOptions);
  }

  /**
   * @param installmentPlanNumber
   * @param refOrderNumber
   * @param extendedParams
   * @param xSplititTouchPoint    TouchPoint
   * @return Response from the API call
   */
  async installmentPlanSearch(
    installmentPlanNumber?: string | null,
    refOrderNumber?: string | null,
    extendedParams?: unknown | null,
    xSplititTouchPoint?: string | null,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InstallmentPlanSearchResponse>> {
    const req = this.createRequest('GET', '/api/installmentplans/search');
    const mapped = req.prepareArgs({
      installmentPlanNumber: [
        installmentPlanNumber,
        optional(nullable(string())),
      ],
      refOrderNumber: [refOrderNumber, optional(nullable(string()))],
      extendedParams: [extendedParams, optional(nullable(unknown()))],
      xSplititTouchPoint: [xSplititTouchPoint, optional(nullable(string()))],
    });
    req.header('X-Splitit-TouchPoint', mapped.xSplititTouchPoint);
    req.query('installmentPlanNumber', mapped.installmentPlanNumber);
    req.query('refOrderNumber', mapped.refOrderNumber);
    req.query('extendedParams', mapped.extendedParams);
    req.throwOn(401, FailedResponseError, '');
    req.throwOn(403, FailedResponseError, '');
    req.throwOn(404, FailedResponseError, '');
    req.throwOn(500, FailedResponseError, '');
    req.authenticate([{ oAuth2Sandbox: true }, { oAuth2Production: true }]);
    return req.callAsJson(installmentPlanSearchResponseSchema, requestOptions);
  }

  /**
   * @param xSplititIdempotencyKey
   * @param body
   * @param xSplititTestMode
   * @param xSplititTouchPoint       TouchPoint
   * @return Response from the API call
   */
  async installmentPlanPost(
    xSplititIdempotencyKey: string,
    body: InstallmentPlanInitiateRequest,
    xSplititTestMode?: TestModesEnum | null,
    xSplititTouchPoint?: string | null,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InitiatePlanResponse>> {
    const req = this.createRequest('POST', '/api/installmentplans/initiate');
    const mapped = req.prepareArgs({
      xSplititIdempotencyKey: [xSplititIdempotencyKey, string()],
      body: [body, installmentPlanInitiateRequestSchema],
      xSplititTestMode: [
        xSplititTestMode,
        optional(nullable(testModesEnumSchema)),
      ],
      xSplititTouchPoint: [xSplititTouchPoint, optional(nullable(string()))],
    });
    req.header('X-Splitit-IdempotencyKey', mapped.xSplititIdempotencyKey);
    req.header('Content-Type', 'application/json-patch+json');
    req.header('X-Splitit-TestMode', mapped.xSplititTestMode);
    req.header('X-Splitit-TouchPoint', mapped.xSplititTouchPoint);
    req.json(mapped.body);
    req.throwOn(400, PlanErrorResponseError, '');
    req.throwOn(401, FailedResponseError, '');
    req.throwOn(403, FailedResponseError, '');
    req.throwOn(404, FailedResponseError, '');
    req.throwOn(500, FailedResponseError, '');
    req.authenticate([{ oAuth2Sandbox: true }, { oAuth2Production: true }]);
    return req.callAsJson(initiatePlanResponseSchema, requestOptions);
  }

  /**
   * @param xSplititIdempotencyKey
   * @param body
   * @param xSplititTestMode
   * @param xSplititTouchPoint       TouchPoint
   * @return Response from the API call
   */
  async installmentPlanPost2(
    xSplititIdempotencyKey: string,
    body: InstallmentPlanCreateRequest,
    xSplititTestMode?: TestModesEnum | null,
    xSplititTouchPoint?: string | null,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InstallmentPlanCreateResponse>> {
    const req = this.createRequest('POST', '/api/installmentplans');
    const mapped = req.prepareArgs({
      xSplititIdempotencyKey: [xSplititIdempotencyKey, string()],
      body: [body, installmentPlanCreateRequestSchema],
      xSplititTestMode: [
        xSplititTestMode,
        optional(nullable(testModesEnumSchema)),
      ],
      xSplititTouchPoint: [xSplititTouchPoint, optional(nullable(string()))],
    });
    req.header('X-Splitit-IdempotencyKey', mapped.xSplititIdempotencyKey);
    req.header('Content-Type', 'application/json-patch+json');
    req.header('X-Splitit-TestMode', mapped.xSplititTestMode);
    req.header('X-Splitit-TouchPoint', mapped.xSplititTouchPoint);
    req.json(mapped.body);
    req.throwOn(400, PlanErrorResponseError, '');
    req.throwOn(401, FailedResponseError, '');
    req.throwOn(403, FailedResponseError, '');
    req.throwOn(404, FailedResponseError, '');
    req.throwOn(500, FailedResponseError, '');
    req.authenticate([{ oAuth2Sandbox: true }, { oAuth2Production: true }]);
    return req.callAsJson(installmentPlanCreateResponseSchema, requestOptions);
  }

  /**
   * @param installmentPlanNumber
   * @param xSplititTouchPoint    TouchPoint
   * @return Response from the API call
   */
  async installmentPlanVerifyAuthorization(
    installmentPlanNumber: string,
    xSplititTouchPoint?: string | null,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<VerifyAuthorizationResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      installmentPlanNumber: [installmentPlanNumber, string()],
      xSplititTouchPoint: [xSplititTouchPoint, optional(nullable(string()))],
    });
    req.header('X-Splitit-TouchPoint', mapped.xSplititTouchPoint);
    req.appendTemplatePath`/api/installmentplans/${mapped.installmentPlanNumber}/verifyauthorization`;
    req.throwOn(401, FailedResponseError, '');
    req.throwOn(403, FailedResponseError, '');
    req.throwOn(404, FailedResponseError, '');
    req.throwOn(500, FailedResponseError, '');
    req.authenticate([{ oAuth2Sandbox: true }, { oAuth2Production: true }]);
    return req.callAsJson(verifyAuthorizationResponseSchema, requestOptions);
  }

  /**
   * @param installmentPlanNumber
   * @param xSplititIdempotencyKey
   * @param body
   * @param xSplititTouchPoint       TouchPoint
   * @return Response from the API call
   */
  async installmentPlanUpdateOrder(
    installmentPlanNumber: string,
    xSplititIdempotencyKey: string,
    body: InstallmentPlanUpdateRequest,
    xSplititTouchPoint?: string | null,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InstallmentPlanUpdateResponse>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      installmentPlanNumber: [installmentPlanNumber, string()],
      xSplititIdempotencyKey: [xSplititIdempotencyKey, string()],
      body: [body, installmentPlanUpdateRequestSchema],
      xSplititTouchPoint: [xSplititTouchPoint, optional(nullable(string()))],
    });
    req.header('X-Splitit-IdempotencyKey', mapped.xSplititIdempotencyKey);
    req.header('Content-Type', 'application/json-patch+json');
    req.header('X-Splitit-TouchPoint', mapped.xSplititTouchPoint);
    req.json(mapped.body);
    req.appendTemplatePath`/api/installmentplans/${mapped.installmentPlanNumber}/updateorder`;
    req.throwOn(401, FailedResponseError, '');
    req.throwOn(403, FailedResponseError, '');
    req.throwOn(404, FailedResponseError, '');
    req.throwOn(500, FailedResponseError, '');
    req.authenticate([{ oAuth2Sandbox: true }, { oAuth2Production: true }]);
    return req.callAsJson(installmentPlanUpdateResponseSchema, requestOptions);
  }

  /**
   * @param xSplititIdempotencyKey
   * @param body
   * @param xSplititTouchPoint       TouchPoint
   * @return Response from the API call
   */
  async installmentPlanUpdateOrder2(
    xSplititIdempotencyKey: string,
    body: InstallmentPlanUpdateRequestByIdentifier,
    xSplititTouchPoint?: string | null,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InstallmentPlanUpdateResponse>> {
    const req = this.createRequest('PUT', '/api/installmentplans/updateorder');
    const mapped = req.prepareArgs({
      xSplititIdempotencyKey: [xSplititIdempotencyKey, string()],
      body: [body, installmentPlanUpdateRequestByIdentifierSchema],
      xSplititTouchPoint: [xSplititTouchPoint, optional(nullable(string()))],
    });
    req.header('X-Splitit-IdempotencyKey', mapped.xSplititIdempotencyKey);
    req.header('Content-Type', 'application/json-patch+json');
    req.header('X-Splitit-TouchPoint', mapped.xSplititTouchPoint);
    req.json(mapped.body);
    req.throwOn(401, FailedResponseError, '');
    req.throwOn(403, FailedResponseError, '');
    req.throwOn(404, FailedResponseError, '');
    req.throwOn(500, FailedResponseError, '');
    req.authenticate([{ oAuth2Sandbox: true }, { oAuth2Production: true }]);
    return req.callAsJson(installmentPlanUpdateResponseSchema, requestOptions);
  }

  /**
   * @param installmentPlanNumber
   * @param xSplititIdempotencyKey
   * @param body
   * @param xSplititTouchPoint       TouchPoint
   * @return Response from the API call
   */
  async installmentPlanRefund(
    installmentPlanNumber: string,
    xSplititIdempotencyKey: string,
    body: InstallmentPlanRefundRequest,
    xSplititTouchPoint?: string | null,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InstallmentPlanRefundResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      installmentPlanNumber: [installmentPlanNumber, string()],
      xSplititIdempotencyKey: [xSplititIdempotencyKey, string()],
      body: [body, installmentPlanRefundRequestSchema],
      xSplititTouchPoint: [xSplititTouchPoint, optional(nullable(string()))],
    });
    req.header('X-Splitit-IdempotencyKey', mapped.xSplititIdempotencyKey);
    req.header('Content-Type', 'application/json-patch+json');
    req.header('X-Splitit-TouchPoint', mapped.xSplititTouchPoint);
    req.json(mapped.body);
    req.appendTemplatePath`/api/installmentplans/${mapped.installmentPlanNumber}/refund`;
    req.throwOn(401, FailedResponseError, '');
    req.throwOn(403, FailedResponseError, '');
    req.throwOn(404, FailedResponseError, '');
    req.throwOn(500, FailedResponseError, '');
    req.authenticate([{ oAuth2Sandbox: true }, { oAuth2Production: true }]);
    return req.callAsJson(installmentPlanRefundResponseSchema, requestOptions);
  }

  /**
   * @param xSplititIdempotencyKey
   * @param body
   * @param xSplititTouchPoint       TouchPoint
   * @return Response from the API call
   */
  async installmentPlanCheckEligibility(
    xSplititIdempotencyKey: string,
    body: CheckInstallmentsEligibilityRequest,
    xSplititTouchPoint?: string | null,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InstallmentsEligibilityResponse>> {
    const req = this.createRequest(
      'POST',
      '/api/installmentplans/check-eligibility'
    );
    const mapped = req.prepareArgs({
      xSplititIdempotencyKey: [xSplititIdempotencyKey, string()],
      body: [body, checkInstallmentsEligibilityRequestSchema],
      xSplititTouchPoint: [xSplititTouchPoint, optional(nullable(string()))],
    });
    req.header('X-Splitit-IdempotencyKey', mapped.xSplititIdempotencyKey);
    req.header('Content-Type', 'application/json-patch+json');
    req.header('X-Splitit-TouchPoint', mapped.xSplititTouchPoint);
    req.json(mapped.body);
    req.throwOn(401, FailedResponseError, '');
    req.throwOn(403, FailedResponseError, '');
    req.throwOn(404, FailedResponseError, '');
    req.throwOn(500, FailedResponseError, '');
    req.authenticate([{ oAuth2Sandbox: true }, { oAuth2Production: true }]);
    return req.callAsJson(
      installmentsEligibilityResponseSchema,
      requestOptions
    );
  }

  /**
   * @param ipn
   * @param xSplititTouchPoint   TouchPoint
   * @return Response from the API call
   */
  async installmentPlanGetEligibilityTermsAndCondition(
    ipn: string,
    xSplititTouchPoint?: string | null,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<EligibilityTermsAndConditionResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      ipn: [ipn, string()],
      xSplititTouchPoint: [xSplititTouchPoint, optional(nullable(string()))],
    });
    req.header('X-Splitit-TouchPoint', mapped.xSplititTouchPoint);
    req.appendTemplatePath`/api/installmentplans/${mapped.ipn}/legal`;
    req.throwOn(401, FailedResponseError, '');
    req.throwOn(403, FailedResponseError, '');
    req.throwOn(404, FailedResponseError, '');
    req.throwOn(500, FailedResponseError, '');
    req.authenticate([{ oAuth2Sandbox: true }, { oAuth2Production: true }]);
    return req.callAsJson(
      eligibilityTermsAndConditionResponseSchema,
      requestOptions
    );
  }
}
