/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface AddressData {
  addressLine?: string;
  addressLine2?: string;
  city?: string;
  country?: string;
  state?: string;
  zip?: string;
}

export const addressDataSchema: Schema<AddressData> = object({
  addressLine: ['AddressLine', optional(string())],
  addressLine2: ['AddressLine2', optional(string())],
  city: ['City', optional(string())],
  country: ['Country', optional(string())],
  state: ['State', optional(string())],
  zip: ['Zip', optional(string())],
});
