/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  GwAuthorizationStatusEnum,
  gwAuthorizationStatusEnumSchema,
} from './gwAuthorizationStatusEnum.js';
import {
  ThreeDsRedirectDataV3,
  threeDsRedirectDataV3Schema,
} from './threeDsRedirectDataV3.js';

export interface AuthorizationModel {
  status: GwAuthorizationStatusEnum;
  date?: string;
  splititErrorResultCode?: string;
  gatewayTransactionID?: string;
  gatewayResultCode?: string;
  gatewayResultMessage?: string;
  threeDSRedirect?: ThreeDsRedirectDataV3;
  cAVV?: string;
  eCI?: string;
  gatewaySourceResponse?: string;
}

export const authorizationModelSchema: Schema<AuthorizationModel> = lazy(() =>
  object({
    status: ['Status', gwAuthorizationStatusEnumSchema],
    date: ['Date', optional(string())],
    splititErrorResultCode: ['SplititErrorResultCode', optional(string())],
    gatewayTransactionID: ['GatewayTransactionID', optional(string())],
    gatewayResultCode: ['GatewayResultCode', optional(string())],
    gatewayResultMessage: ['GatewayResultMessage', optional(string())],
    threeDSRedirect: ['ThreeDSRedirect', optional(threeDsRedirectDataV3Schema)],
    cAVV: ['CAVV', optional(string())],
    eCI: ['ECI', optional(string())],
    gatewaySourceResponse: ['GatewaySourceResponse', optional(string())],
  })
);
