/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface BluesnapVaultedShopperToken {
  token?: string;
  last4Digit?: string;
}

export const bluesnapVaultedShopperTokenSchema: Schema<BluesnapVaultedShopperToken> = object(
  {
    token: ['Token', optional(string())],
    last4Digit: ['Last4Digit', optional(string())],
  }
);
