/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for CardBrandEnum
 */
export enum CardBrandEnum {
  Mastercard = 'Mastercard',
  Visa = 'Visa',
  AmericanExpress = 'AmericanExpress',
  Maestro = 'Maestro',
  JCB = 'JCB',
  CUP = 'CUP',
  UPI = 'UPI',
  Discover = 'Discover',
  Other = 'Other',
}

/**
 * Schema for CardBrandEnum
 */
export const cardBrandEnumSchema: Schema<CardBrandEnum> = stringEnum(
  CardBrandEnum
);
