/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { CardBrandEnum, cardBrandEnumSchema } from './cardBrandEnum.js';
import { CardTypeEnum, cardTypeEnumSchema } from './cardTypeEnum.js';

export interface CardData {
  cardHolderFullName?: string;
  cardNumber?: string;
  cardExpYear?: string;
  cardExpMonth?: string;
  cardCvv?: string;
  cardBrand?: CardBrandEnum;
  cardType?: CardTypeEnum;
}

export const cardDataSchema: Schema<CardData> = object({
  cardHolderFullName: ['CardHolderFullName', optional(string())],
  cardNumber: ['CardNumber', optional(string())],
  cardExpYear: ['CardExpYear', optional(string())],
  cardExpMonth: ['CardExpMonth', optional(string())],
  cardCvv: ['CardCvv', optional(string())],
  cardBrand: ['CardBrand', optional(cardBrandEnumSchema)],
  cardType: ['CardType', optional(cardTypeEnumSchema)],
});
