/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for CardTypeEnum
 */
export enum CardTypeEnum {
  Credit = 'Credit',
  Debit = 'Debit',
  Charge = 'Charge',
  Other = 'Other',
  Prepaid = 'Prepaid',
  VisaDeferredDebit = 'VisaDeferredDebit',
  NetworkOnly = 'NetworkOnly',
}

/**
 * Schema for CardTypeEnum
 */
export const cardTypeEnumSchema: Schema<CardTypeEnum> = stringEnum(
  CardTypeEnum
);
