/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { AddressData, addressDataSchema } from './addressData.js';
import { CardData, cardDataSchema } from './cardData.js';
import { PlanData, planDataSchema } from './planData.js';

export interface CheckInstallmentsEligibilityRequest {
  planData?: PlanData;
  cardDetails?: CardData;
  billingAddress?: AddressData;
  shopperIdentifier?: string;
}

export const checkInstallmentsEligibilityRequestSchema: Schema<CheckInstallmentsEligibilityRequest> = lazy(
  () =>
    object({
      planData: ['PlanData', optional(planDataSchema)],
      cardDetails: ['CardDetails', optional(cardDataSchema)],
      billingAddress: ['BillingAddress', optional(addressDataSchema)],
      shopperIdentifier: ['ShopperIdentifier', optional(string())],
    })
);
