/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface EligibilityTermsAndConditionResponse {
  termsAndConditions?: string;
  privacyPolicy?: string;
  provider?: string;
}

export const eligibilityTermsAndConditionResponseSchema: Schema<EligibilityTermsAndConditionResponse> = object(
  {
    termsAndConditions: ['TermsAndConditions', optional(string())],
    privacyPolicy: ['PrivacyPolicy', optional(string())],
    provider: ['Provider', optional(string())],
  }
);
