/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface Error {
  code?: string;
  message?: string;
  additionalInfo?: string;
}

export const errorSchema: Schema<Error> = object({
  code: ['Code', optional(string())],
  message: ['Message', optional(string())],
  additionalInfo: ['AdditionalInfo', optional(string())],
});
