/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, object, optional, Schema, string } from '../schema.js';

export interface ErrorExtended {
  code?: string;
  message?: string;
  additionalInfo?: string;
  extraData?: Record<string, string>;
}

export const errorExtendedSchema: Schema<ErrorExtended> = object({
  code: ['Code', optional(string())],
  message: ['Message', optional(string())],
  additionalInfo: ['AdditionalInfo', optional(string())],
  extraData: ['ExtraData', optional(dict(string()))],
});
