/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for GwAuthorizationStatusEnum
 */
export enum GwAuthorizationStatusEnum {
  NA = 'NA',
  Succeeded = 'Succeeded',
  Pending3DS = 'Pending3DS',
  Failed = 'Failed',
  Canceled = 'Canceled',
  Voided = 'Voided',
}

/**
 * Schema for GwAuthorizationStatusEnum
 */
export const gwAuthorizationStatusEnumSchema: Schema<GwAuthorizationStatusEnum> = stringEnum(
  GwAuthorizationStatusEnum
);
