/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, object, optional, Schema, string } from '../schema.js';

export interface IdentifierContract {
  refOrderNumber?: string;
  installmentPlanNumber?: string;
  extendedParams?: Record<string, string>;
}

export const identifierContractSchema: Schema<IdentifierContract> = object({
  refOrderNumber: ['RefOrderNumber', optional(string())],
  installmentPlanNumber: ['InstallmentPlanNumber', optional(string())],
  extendedParams: ['ExtendedParams', optional(dict(string()))],
});
