/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface InitiateRedirectionEndpointsModel {
  succeeded?: string;
  failed?: string;
  cancel?: string;
}

export const initiateRedirectionEndpointsModelSchema: Schema<InitiateRedirectionEndpointsModel> = object(
  {
    succeeded: ['Succeeded', optional(string())],
    failed: ['Failed', optional(string())],
    cancel: ['Cancel', optional(string())],
  }
);
