/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { AddressData, addressDataSchema } from './addressData.js';
import { PlanStatusEnum, planStatusEnumSchema } from './planStatusEnum.js';
import {
  PurchaseMethodEnum,
  purchaseMethodEnumSchema,
} from './purchaseMethodEnum.js';
import { ShopperData, shopperDataSchema } from './shopperData.js';

export interface InitiatePlanResponse {
  installmentPlanNumber?: string;
  refOrderNumber?: string;
  purchaseMethod?: PurchaseMethodEnum;
  status: PlanStatusEnum;
  currency?: string;
  amount?: number;
  extendedParams?: Record<string, string>;
  shopper?: ShopperData;
  billingAddress?: AddressData;
  checkoutUrl?: string;
  principalAmount?: number;
}

export const initiatePlanResponseSchema: Schema<InitiatePlanResponse> = lazy(
  () =>
    object({
      installmentPlanNumber: ['InstallmentPlanNumber', optional(string())],
      refOrderNumber: ['RefOrderNumber', optional(string())],
      purchaseMethod: ['PurchaseMethod', optional(purchaseMethodEnumSchema)],
      status: ['Status', planStatusEnumSchema],
      currency: ['Currency', optional(string())],
      amount: ['Amount', optional(number())],
      extendedParams: ['ExtendedParams', optional(dict(string()))],
      shopper: ['Shopper', optional(shopperDataSchema)],
      billingAddress: ['BillingAddress', optional(addressDataSchema)],
      checkoutUrl: ['CheckoutUrl', optional(string())],
      principalAmount: ['PrincipalAmount', optional(number())],
    })
);
