/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema.js';
import {
  InstallmentStatusEnum,
  installmentStatusEnumSchema,
} from './installmentStatusEnum.js';

export interface Installment {
  installmentNumber: number;
  amount: number;
  processDateTime?: string;
  status: InstallmentStatusEnum;
}

export const installmentSchema: Schema<Installment> = object({
  installmentNumber: ['InstallmentNumber', number()],
  amount: ['Amount', number()],
  processDateTime: ['ProcessDateTime', optional(string())],
  status: ['Status', installmentStatusEnumSchema],
});
