/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for InstallmentStatusEnum
 */
export enum InstallmentStatusEnum {
  Pending = 'Pending',
  Processed = 'Processed',
  Canceled = 'Canceled',
}

/**
 * Schema for InstallmentStatusEnum
 */
export const installmentStatusEnumSchema: Schema<InstallmentStatusEnum> = stringEnum(
  InstallmentStatusEnum
);
