/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema.js';
import { PlanStatusEnum, planStatusEnumSchema } from './planStatusEnum.js';
import {
  ShippingStatusEnum,
  shippingStatusEnumSchema,
} from './shippingStatusEnum.js';

export interface InstallmentPlanUpdateResponse {
  refOrderNumber?: string;
  installmentPlanNumber?: string;
  status: PlanStatusEnum;
  shippingStatus: ShippingStatusEnum;
  newAmount?: number;
}

export const installmentPlanUpdateResponseSchema: Schema<InstallmentPlanUpdateResponse> = object(
  {
    refOrderNumber: ['RefOrderNumber', optional(string())],
    installmentPlanNumber: ['InstallmentPlanNumber', optional(string())],
    status: ['Status', planStatusEnumSchema],
    shippingStatus: ['ShippingStatus', shippingStatusEnumSchema],
    newAmount: ['NewAmount', optional(number())],
  }
);
