/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  IdentifierContract,
  identifierContractSchema,
} from './identifierContract.js';
import {
  ShippingStatusEnum,
  shippingStatusEnumSchema,
} from './shippingStatusEnum.js';

export interface InstallmentPlanUpdateRequestByIdentifier {
  refOrderNumber?: string;
  trackingNumber?: string;
  capture?: boolean;
  shippingStatus?: ShippingStatusEnum;
  newAmount?: number;
  identifier?: IdentifierContract;
}

export const installmentPlanUpdateRequestByIdentifierSchema: Schema<InstallmentPlanUpdateRequestByIdentifier> = lazy(
  () =>
    object({
      refOrderNumber: ['RefOrderNumber', optional(string())],
      trackingNumber: ['TrackingNumber', optional(string())],
      capture: ['Capture', optional(boolean())],
      shippingStatus: ['ShippingStatus', optional(shippingStatusEnumSchema)],
      newAmount: ['NewAmount', optional(number())],
      identifier: ['Identifier', optional(identifierContractSchema)],
    })
);
