/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import {
  RefundStrategyEnum,
  refundStrategyEnumSchema,
} from './refundStrategyEnum.js';

export interface InstallmentPlanRefundRequest {
  amount: string;
  refundStrategy?: RefundStrategyEnum;
  referenceId?: string;
}

export const installmentPlanRefundRequestSchema: Schema<InstallmentPlanRefundRequest> = object(
  {
    amount: ['Amount', string()],
    refundStrategy: ['RefundStrategy', optional(refundStrategyEnumSchema)],
    referenceId: ['ReferenceId', optional(string())],
  }
);
