/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema.js';
import {
  ShippingStatusEnum,
  shippingStatusEnumSchema,
} from './shippingStatusEnum.js';

export interface InstallmentPlanUpdateRequest {
  refOrderNumber?: string;
  trackingNumber?: string;
  capture?: boolean;
  shippingStatus?: ShippingStatusEnum;
  newAmount?: string;
}

export const installmentPlanUpdateRequestSchema: Schema<InstallmentPlanUpdateRequest> = object(
  {
    refOrderNumber: ['RefOrderNumber', optional(string())],
    trackingNumber: ['TrackingNumber', optional(string())],
    capture: ['Capture', optional(boolean())],
    shippingStatus: ['ShippingStatus', optional(shippingStatusEnumSchema)],
    newAmount: ['NewAmount', optional(string())],
  }
);
