/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  SearchInstallmentPlanResponseItem,
  searchInstallmentPlanResponseItemSchema,
} from './searchInstallmentPlanResponseItem.js';

export interface InstallmentPlanSearchResponse {
  planList?: SearchInstallmentPlanResponseItem[];
}

export const installmentPlanSearchResponseSchema: Schema<InstallmentPlanSearchResponse> = lazy(
  () =>
    object({
      planList: [
        'PlanList',
        optional(array(searchInstallmentPlanResponseItemSchema)),
      ],
    })
);
