/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  PaymentPlanOptionModel,
  paymentPlanOptionModelSchema,
} from './paymentPlanOptionModel.js';

export interface InstallmentsEligibilityResponse {
  installmentProvider?: string;
  paymentPlanOptions?: PaymentPlanOptionModel[];
}

export const installmentsEligibilityResponseSchema: Schema<InstallmentsEligibilityResponse> = lazy(
  () =>
    object({
      installmentProvider: ['InstallmentProvider', optional(string())],
      paymentPlanOptions: [
        'PaymentPlanOptions',
        optional(array(paymentPlanOptionModelSchema)),
      ],
    })
);
