/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { AddressData, addressDataSchema } from './addressData.js';
import {
  AuthorizationModel,
  authorizationModelSchema,
} from './authorizationModel.js';
import { Installment, installmentSchema } from './installment.js';
import { LinksData, linksDataSchema } from './linksData.js';
import {
  PaymentMethodModel,
  paymentMethodModelSchema,
} from './paymentMethodModel.js';
import { PlanStatusEnum, planStatusEnumSchema } from './planStatusEnum.js';
import {
  PurchaseMethodEnum,
  purchaseMethodEnumSchema,
} from './purchaseMethodEnum.js';
import { ShopperData, shopperDataSchema } from './shopperData.js';

export interface InstallmentPlanCreateResponse {
  installmentPlanNumber?: string;
  dateCreated: string;
  refOrderNumber?: string;
  purchaseMethod?: PurchaseMethodEnum;
  status: PlanStatusEnum;
  currency?: string;
  originalAmount?: number;
  amount?: number;
  extendedParams?: Record<string, string>;
  authorization?: AuthorizationModel;
  shopper?: ShopperData;
  billingAddress?: AddressData;
  paymentMethod?: PaymentMethodModel;
  installments?: Installment[];
  links?: LinksData;
}

export const installmentPlanCreateResponseSchema: Schema<InstallmentPlanCreateResponse> = lazy(
  () =>
    object({
      installmentPlanNumber: ['InstallmentPlanNumber', optional(string())],
      dateCreated: ['DateCreated', string()],
      refOrderNumber: ['RefOrderNumber', optional(string())],
      purchaseMethod: ['PurchaseMethod', optional(purchaseMethodEnumSchema)],
      status: ['Status', planStatusEnumSchema],
      currency: ['Currency', optional(string())],
      originalAmount: ['OriginalAmount', optional(number())],
      amount: ['Amount', optional(number())],
      extendedParams: ['ExtendedParams', optional(dict(string()))],
      authorization: ['Authorization', optional(authorizationModelSchema)],
      shopper: ['Shopper', optional(shopperDataSchema)],
      billingAddress: ['BillingAddress', optional(addressDataSchema)],
      paymentMethod: ['PaymentMethod', optional(paymentMethodModelSchema)],
      installments: ['Installments', optional(array(installmentSchema))],
      links: ['Links', optional(linksDataSchema)],
    })
);
