/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema.js';
import { RefundSummary, refundSummarySchema } from './refundSummary.js';

export interface InstallmentPlanRefundResponse {
  refundId?: string;
  installmentPlanNumber?: string;
  currency?: string;
  nonCreditRefundAmount?: number;
  creditRefundAmount?: number;
  summary?: RefundSummary;
  referenceId?: string;
}

export const installmentPlanRefundResponseSchema: Schema<InstallmentPlanRefundResponse> = lazy(
  () =>
    object({
      refundId: ['RefundId', optional(string())],
      installmentPlanNumber: ['InstallmentPlanNumber', optional(string())],
      currency: ['Currency', optional(string())],
      nonCreditRefundAmount: ['NonCreditRefundAmount', optional(number())],
      creditRefundAmount: ['CreditRefundAmount', optional(number())],
      summary: ['Summary', optional(refundSummarySchema)],
      referenceId: ['ReferenceId', optional(string())],
    })
);
