/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema } from '../schema.js';
import {
  AddressDataModel,
  addressDataModelSchema,
} from './addressDataModel.js';
import {
  EventsEndpointsModel,
  eventsEndpointsModelSchema,
} from './eventsEndpointsModel.js';
import {
  InitiateRedirectionEndpointsModel,
  initiateRedirectionEndpointsModelSchema,
} from './initiateRedirectionEndpointsModel.js';
import { PlanDataModel, planDataModelSchema } from './planDataModel.js';
import { ProcessingData, processingDataSchema } from './processingData.js';
import { ShopperData, shopperDataSchema } from './shopperData.js';
import { UxSettingsModel, uxSettingsModelSchema } from './uxSettingsModel.js';

export interface InstallmentPlanInitiateRequest {
  autoCapture?: boolean;
  attempt3dSecure?: boolean;
  shopper?: ShopperData;
  planData?: PlanDataModel;
  billingAddress?: AddressDataModel;
  redirectUrls?: InitiateRedirectionEndpointsModel;
  uxSettings?: UxSettingsModel;
  eventsEndpoints?: EventsEndpointsModel;
  processingData?: ProcessingData;
}

export const installmentPlanInitiateRequestSchema: Schema<InstallmentPlanInitiateRequest> = lazy(
  () =>
    object({
      autoCapture: ['AutoCapture', optional(boolean())],
      attempt3dSecure: ['Attempt3dSecure', optional(boolean())],
      shopper: ['Shopper', optional(shopperDataSchema)],
      planData: ['PlanData', optional(planDataModelSchema)],
      billingAddress: ['BillingAddress', optional(addressDataModelSchema)],
      redirectUrls: [
        'RedirectUrls',
        optional(initiateRedirectionEndpointsModelSchema),
      ],
      uxSettings: ['UxSettings', optional(uxSettingsModelSchema)],
      eventsEndpoints: [
        'EventsEndpoints',
        optional(eventsEndpointsModelSchema),
      ],
      processingData: ['ProcessingData', optional(processingDataSchema)],
    })
);
