/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema } from '../schema.js';
import {
  AddressDataModel,
  addressDataModelSchema,
} from './addressDataModel.js';
import {
  EventsEndpointsModel,
  eventsEndpointsModelSchema,
} from './eventsEndpointsModel.js';
import {
  PaymentMethodModel,
  paymentMethodModelSchema,
} from './paymentMethodModel.js';
import { PlanDataModel, planDataModelSchema } from './planDataModel.js';
import { ProcessingData, processingDataSchema } from './processingData.js';
import {
  RedirectionEndpointsModel,
  redirectionEndpointsModelSchema,
} from './redirectionEndpointsModel.js';
import { ShopperData, shopperDataSchema } from './shopperData.js';

export interface InstallmentPlanCreateRequest {
  autoCapture: boolean;
  attempt3dSecure?: boolean;
  termsAndConditionsAccepted: boolean;
  shopper?: ShopperData;
  planData?: PlanDataModel;
  billingAddress?: AddressDataModel;
  paymentMethod?: PaymentMethodModel;
  redirectUrls?: RedirectionEndpointsModel;
  processingData?: ProcessingData;
  eventsEndpoints?: EventsEndpointsModel;
}

export const installmentPlanCreateRequestSchema: Schema<InstallmentPlanCreateRequest> = lazy(
  () =>
    object({
      autoCapture: ['AutoCapture', boolean()],
      attempt3dSecure: ['Attempt3dSecure', optional(boolean())],
      termsAndConditionsAccepted: ['TermsAndConditionsAccepted', boolean()],
      shopper: ['Shopper', optional(shopperDataSchema)],
      planData: ['PlanData', optional(planDataModelSchema)],
      billingAddress: ['BillingAddress', optional(addressDataModelSchema)],
      paymentMethod: ['PaymentMethod', optional(paymentMethodModelSchema)],
      redirectUrls: ['RedirectUrls', optional(redirectionEndpointsModelSchema)],
      processingData: ['ProcessingData', optional(processingDataSchema)],
      eventsEndpoints: [
        'EventsEndpoints',
        optional(eventsEndpointsModelSchema),
      ],
    })
);
