/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface LinksModel {
  privacyPolicyUrl?: string;
  termsAndConditionsUrl?: string;
  learnMoreUrl?: string;
}

export const linksModelSchema: Schema<LinksModel> = object({
  privacyPolicyUrl: ['PrivacyPolicyUrl', optional(string())],
  termsAndConditionsUrl: ['TermsAndConditionsUrl', optional(string())],
  learnMoreUrl: ['LearnMoreUrl', optional(string())],
});
