/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface LinksData {
  checkout?: string;
  learnMore?: string;
  termsConditions?: string;
  privacyPolicy?: string;
}

export const linksDataSchema: Schema<LinksData> = object({
  checkout: ['Checkout', optional(string())],
  learnMore: ['LearnMore', optional(string())],
  termsConditions: ['TermsConditions', optional(string())],
  privacyPolicy: ['PrivacyPolicy', optional(string())],
});
