/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface MockerShopperToken {
  token?: string;
  last4Digit?: string;
}

export const mockerShopperTokenSchema: Schema<MockerShopperToken> = object({
  token: ['Token', optional(string())],
  last4Digit: ['Last4Digit', optional(string())],
});
