/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OAuthScopeOAuth2ProductionEnum
 */
export enum OAuthScopeOAuth2ProductionEnum {
  ApiV3 = 'api.v3',
}

/**
 * Schema for OAuthScopeOAuth2ProductionEnum
 */
export const oAuthScopeOAuth2ProductionEnumSchema: Schema<OAuthScopeOAuth2ProductionEnum> = stringEnum(
  OAuthScopeOAuth2ProductionEnum
);
