/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OAuthScopeOAuth2SandboxEnum
 */
export enum OAuthScopeOAuth2SandboxEnum {
  ApiV3 = 'api.v3',
}

/**
 * Schema for OAuthScopeOAuth2SandboxEnum
 */
export const oAuthScopeOAuth2SandboxEnumSchema: Schema<OAuthScopeOAuth2SandboxEnum> = stringEnum(
  OAuthScopeOAuth2SandboxEnum
);
