/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  BluesnapVaultedShopperToken,
  bluesnapVaultedShopperTokenSchema,
} from './bluesnapVaultedShopperToken.js';
import { CardData, cardDataSchema } from './cardData.js';
import {
  MockerShopperToken,
  mockerShopperTokenSchema,
} from './mockerShopperToken.js';
import {
  PaymentMethodTypeEnum,
  paymentMethodTypeEnumSchema,
} from './paymentMethodTypeEnum.js';
import { SpreedlyToken, spreedlyTokenSchema } from './spreedlyToken.js';

export interface PaymentMethodModel {
  type: PaymentMethodTypeEnum;
  card?: CardData;
  token?: string;
  bluesnapVaultedShopperToken?: BluesnapVaultedShopperToken;
  mockerShopperToken?: MockerShopperToken;
  spreedlyToken?: SpreedlyToken;
  cardPAR?: string;
}

export const paymentMethodModelSchema: Schema<PaymentMethodModel> = lazy(() =>
  object({
    type: ['Type', paymentMethodTypeEnumSchema],
    card: ['Card', optional(cardDataSchema)],
    token: ['Token', optional(string())],
    bluesnapVaultedShopperToken: [
      'BluesnapVaultedShopperToken',
      optional(bluesnapVaultedShopperTokenSchema),
    ],
    mockerShopperToken: [
      'MockerShopperToken',
      optional(mockerShopperTokenSchema),
    ],
    spreedlyToken: ['SpreedlyToken', optional(spreedlyTokenSchema)],
    cardPAR: ['CardPAR', optional(string())],
  })
);
