/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema.js';
import { LinksModel, linksModelSchema } from './linksModel.js';

export interface PaymentPlanOptionModel {
  numberOfInstallments: number;
  firstInstallmentAmount: number;
  installmentAmount: number;
  lastInstallmentAmount: number;
  links?: LinksModel;
  termsAndConditionsBrief?: string;
  installmentFrequency?: string;
}

export const paymentPlanOptionModelSchema: Schema<PaymentPlanOptionModel> = lazy(
  () =>
    object({
      numberOfInstallments: ['NumberOfInstallments', number()],
      firstInstallmentAmount: ['FirstInstallmentAmount', number()],
      installmentAmount: ['InstallmentAmount', number()],
      lastInstallmentAmount: ['LastInstallmentAmount', number()],
      links: ['Links', optional(linksModelSchema)],
      termsAndConditionsBrief: ['TermsAndConditionsBrief', optional(string())],
      installmentFrequency: ['InstallmentFrequency', optional(string())],
    })
);
