/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PaymentMethodTypeEnum
 */
export enum PaymentMethodTypeEnum {
  Card = 'Card',
  SplititToken = 'SplititToken',
  BluesnapVaultedShopperToken = 'BluesnapVaultedShopperToken',
  SplititMockerV2Token = 'SplititMockerV2Token',
  SpreedlyToken = 'SpreedlyToken',
}

/**
 * Schema for PaymentMethodTypeEnum
 */
export const paymentMethodTypeEnumSchema: Schema<PaymentMethodTypeEnum> = stringEnum(
  PaymentMethodTypeEnum
);
