/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { CardTypeEnum, cardTypeEnumSchema } from './cardTypeEnum.js';

export interface PaymentInfo {
  cardBin?: string;
  cardType?: CardTypeEnum;
}

export const paymentInfoSchema: Schema<PaymentInfo> = object({
  cardBin: ['CardBin', optional(string())],
  cardType: ['CardType', optional(cardTypeEnumSchema)],
});
