/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PlanStatusEnum
 */
export enum PlanStatusEnum {
  Initialized = 'Initialized',
  PendingCapture = 'PendingCapture',
  Active = 'Active',
  Cleared = 'Cleared',
  Canceled = 'Canceled',
}

/**
 * Schema for PlanStatusEnum
 */
export const planStatusEnumSchema: Schema<PlanStatusEnum> = stringEnum(
  PlanStatusEnum
);
