/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  PurchaseMethodEnum,
  purchaseMethodEnumSchema,
} from './purchaseMethodEnum.js';

export interface PlanDataModel {
  totalAmount: string;
  currency?: string;
  numberOfInstallments?: number | null;
  terminalId?: string;
  purchaseMethod: PurchaseMethodEnum;
  refOrderNumber?: string;
  extendedParams?: Record<string, string>;
  firstInstallmentAmount?: string;
  firstInstallmentDate?: string;
}

export const planDataModelSchema: Schema<PlanDataModel> = object({
  totalAmount: ['TotalAmount', string()],
  currency: ['Currency', optional(string())],
  numberOfInstallments: ['NumberOfInstallments', optional(nullable(number()))],
  terminalId: ['TerminalId', optional(string())],
  purchaseMethod: ['PurchaseMethod', purchaseMethodEnumSchema],
  refOrderNumber: ['RefOrderNumber', optional(string())],
  extendedParams: ['ExtendedParams', optional(dict(string()))],
  firstInstallmentAmount: ['FirstInstallmentAmount', optional(string())],
  firstInstallmentDate: ['FirstInstallmentDate', optional(string())],
});
