/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { ProcessingData, processingDataSchema } from './processingData.js';
import {
  PurchaseMethodEnum,
  purchaseMethodEnumSchema,
} from './purchaseMethodEnum.js';

export interface PlanData {
  terminalId?: string;
  totalAmount: string;
  firstInstallmentAmount?: number;
  currency?: string;
  numberOfInstallments: number;
  purchaseMethod: PurchaseMethodEnum;
  refOrderNumber?: string;
  allowedInstallmentOptions?: number[];
  tags?: Record<string, string>;
  processingData?: ProcessingData;
  firstInstallmentDate?: string;
}

export const planDataSchema: Schema<PlanData> = lazy(() =>
  object({
    terminalId: ['TerminalId', optional(string())],
    totalAmount: ['TotalAmount', string()],
    firstInstallmentAmount: ['FirstInstallmentAmount', optional(number())],
    currency: ['Currency', optional(string())],
    numberOfInstallments: ['NumberOfInstallments', number()],
    purchaseMethod: ['PurchaseMethod', purchaseMethodEnumSchema],
    refOrderNumber: ['RefOrderNumber', optional(string())],
    allowedInstallmentOptions: [
      'AllowedInstallmentOptions',
      optional(array(number())),
    ],
    tags: ['Tags', optional(dict(string()))],
    processingData: ['ProcessingData', optional(processingDataSchema)],
    firstInstallmentDate: ['FirstInstallmentDate', optional(string())],
  })
);
