/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema, string } from '../schema.js';
import { ThreeDSData, threeDSDataSchema } from './threeDSData.js';

export interface ProcessingData {
  attemptThreeDSecured?: boolean;
  softDescriptor?: string;
  threeDSData?: ThreeDSData;
}

export const processingDataSchema: Schema<ProcessingData> = lazy(() =>
  object({
    attemptThreeDSecured: ['AttemptThreeDSecured', optional(boolean())],
    softDescriptor: ['SoftDescriptor', optional(string())],
    threeDSData: ['ThreeDSData', optional(threeDSDataSchema)],
  })
);
