/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PurchaseMethodEnum
 */
export enum PurchaseMethodEnum {
  InStore = 'InStore',
  PhoneOrder = 'PhoneOrder',
  ECommerce = 'ECommerce',
}

/**
 * Schema for PurchaseMethodEnum
 */
export const purchaseMethodEnumSchema: Schema<PurchaseMethodEnum> = stringEnum(
  PurchaseMethodEnum
);
