/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface RedirectionEndpointsModel {
  authorizeSucceeded?: string;
  succeeded?: string;
  authorizeFailed?: string;
  failed?: string;
}

export const redirectionEndpointsModelSchema: Schema<RedirectionEndpointsModel> = object(
  {
    authorizeSucceeded: ['AuthorizeSucceeded', optional(string())],
    succeeded: ['Succeeded', optional(string())],
    authorizeFailed: ['AuthorizeFailed', optional(string())],
    failed: ['Failed', optional(string())],
  }
);
