/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for RefundStatusEnum
 */
export enum RefundStatusEnum {
  Pending = 'Pending',
  Succeeded = 'Succeeded',
  Failed = 'Failed',
}

/**
 * Schema for RefundStatusEnum
 */
export const refundStatusEnumSchema: Schema<RefundStatusEnum> = stringEnum(
  RefundStatusEnum
);
