/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for RefundStrategyEnum
 */
export enum RefundStrategyEnum {
  FutureInstallmentsFirst = 'FutureInstallmentsFirst',
  FutureInstallmentsLast = 'FutureInstallmentsLast',
  FutureInstallmentsNotAllowed = 'FutureInstallmentsNotAllowed',
  ReduceFromLastInstallment = 'ReduceFromLastInstallment',
}

/**
 * Schema for RefundStrategyEnum
 */
export const refundStrategyEnumSchema: Schema<RefundStrategyEnum> = stringEnum(
  RefundStrategyEnum
);
