/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema.js';

export interface RefundSummary {
  totalAmount?: number;
  failedAmount?: number;
  succeededAmount?: number;
  pendingAmount?: number;
}

export const refundSummarySchema: Schema<RefundSummary> = object({
  totalAmount: ['TotalAmount', optional(number())],
  failedAmount: ['FailedAmount', optional(number())],
  succeededAmount: ['SucceededAmount', optional(number())],
  pendingAmount: ['PendingAmount', optional(number())],
});
