/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema.js';
import {
  RefundStatusEnum,
  refundStatusEnumSchema,
} from './refundStatusEnum.js';

export interface RefundModel {
  refundId?: string;
  submitDate: string;
  totalAmount: number;
  status: RefundStatusEnum;
  nonCreditRefundAmount: number;
  creditRefundAmount: number;
  referenceId?: string;
}

export const refundModelSchema: Schema<RefundModel> = object({
  refundId: ['RefundId', optional(string())],
  submitDate: ['SubmitDate', string()],
  totalAmount: ['TotalAmount', number()],
  status: ['Status', refundStatusEnumSchema],
  nonCreditRefundAmount: ['NonCreditRefundAmount', number()],
  creditRefundAmount: ['CreditRefundAmount', number()],
  referenceId: ['ReferenceId', optional(string())],
});
