/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ShippingStatusEnum
 */
export enum ShippingStatusEnum {
  Pending = 'Pending',
  Shipped = 'Shipped',
  Delivered = 'Delivered',
}

/**
 * Schema for ShippingStatusEnum
 */
export const shippingStatusEnumSchema: Schema<ShippingStatusEnum> = stringEnum(
  ShippingStatusEnum
);
