/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface ShopperData {
  fullName?: string;
  email?: string;
  phoneNumber?: string;
  culture?: string;
  externalId?: string;
}

export const shopperDataSchema: Schema<ShopperData> = object({
  fullName: ['FullName', optional(string())],
  email: ['Email', optional(string())],
  phoneNumber: ['PhoneNumber', optional(string())],
  culture: ['Culture', optional(string())],
  externalId: ['ExternalId', optional(string())],
});
