/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TestModesEnum
 */
export enum TestModesEnum {
  None = 'None',
  Regular = 'Regular',
  Fast = 'Fast',
  Automation = 'Automation',
}

/**
 * Schema for TestModesEnum
 */
export const testModesEnumSchema: Schema<TestModesEnum> = stringEnum(
  TestModesEnum
);
