/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface ThreeDSData {
  eCI?: string;
  cAVV?: string;
  xID?: string;
  directoryServerTxnId?: string;
  threeDSVersion?: string;
  transactionId?: string;
}

export const threeDSDataSchema: Schema<ThreeDSData> = object({
  eCI: ['ECI', optional(string())],
  cAVV: ['CAVV', optional(string())],
  xID: ['XID', optional(string())],
  directoryServerTxnId: ['DirectoryServerTxnId', optional(string())],
  threeDSVersion: ['ThreeDSVersion', optional(string())],
  transactionId: ['TransactionId', optional(string())],
});
