/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, object, optional, Schema, string } from '../schema.js';

export interface ThreeDsRedirectDataV3 {
  url?: string;
  verb?: string;
  params?: Record<string, string>;
  clientRedirectUrl?: string;
}

export const threeDsRedirectDataV3Schema: Schema<ThreeDsRedirectDataV3> = object(
  {
    url: ['Url', optional(string())],
    verb: ['Verb', optional(string())],
    params: ['Params', optional(dict(string()))],
    clientRedirectUrl: ['ClientRedirectUrl', optional(string())],
  }
);
