/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema } from '../schema.js';

export interface UxSettingsModel {
  displayedInstallmentOptions?: number[];
}

export const uxSettingsModelSchema: Schema<UxSettingsModel> = object({
  displayedInstallmentOptions: [
    'DisplayedInstallmentOptions',
    optional(array(number())),
  ],
});
