/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, number, object, optional, Schema } from '../schema.js';
import {
  AuthorizationModel,
  authorizationModelSchema,
} from './authorizationModel.js';

export interface VerifyAuthorizationResponse {
  isAuthorized: boolean;
  authorizationAmount?: number;
  authorization?: AuthorizationModel;
}

export const verifyAuthorizationResponseSchema: Schema<VerifyAuthorizationResponse> = lazy(
  () =>
    object({
      isAuthorized: ['IsAuthorized', boolean()],
      authorizationAmount: ['AuthorizationAmount', optional(number())],
      authorization: ['Authorization', optional(authorizationModelSchema)],
    })
);
