/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  compositeAuthenticationProvider,
  OAuthConfiguration,
  requestAuthenticationProvider,
} from './authentication.js';
import { Configuration } from './configuration.js';
import { OAuthToken } from './models/oAuthToken.js';
import { OAuth2ProductionManager } from './oAuth2ProductionManager.js';
import { OAuth2SandboxManager } from './oAuth2SandboxManager.js';

export function createAuthProviderFromConfig(
  config: Partial<Configuration>,
  oAuth2Sandbox: () => OAuth2SandboxManager | undefined,
  oAuth2Production: () => OAuth2ProductionManager | undefined
) {
  const authConfig = {
    oAuth2Sandbox:
      config.oAuth2SandboxCredentials &&
      requestAuthenticationProvider(
        config.oAuth2SandboxCredentials.oAuthToken,
        oAuth2SandboxTokenProvider(
          oAuth2Sandbox,
          config.oAuth2SandboxCredentials.oAuthTokenProvider
        ),
        config.oAuth2SandboxCredentials.oAuthOnTokenUpdate,
        {
          clockSkew: config.oAuth2SandboxCredentials.oAuthClockSkew,
        } as OAuthConfiguration
      ),
    oAuth2Production:
      config.oAuth2ProductionCredentials &&
      requestAuthenticationProvider(
        config.oAuth2ProductionCredentials.oAuthToken,
        oAuth2ProductionTokenProvider(
          oAuth2Production,
          config.oAuth2ProductionCredentials.oAuthTokenProvider
        ),
        config.oAuth2ProductionCredentials.oAuthOnTokenUpdate,
        {
          clockSkew: config.oAuth2ProductionCredentials.oAuthClockSkew,
        } as OAuthConfiguration
      ),
  };

  return compositeAuthenticationProvider<
    keyof typeof authConfig,
    typeof authConfig
  >(authConfig);
}

function oAuth2SandboxTokenProvider(
  oAuth2Sandbox: () => OAuth2SandboxManager | undefined,
  defaultProvider:
    | ((
        lastOAuthToken: OAuthToken | undefined,
        authManager: OAuth2SandboxManager
      ) => Promise<OAuthToken>)
    | undefined
): ((token: OAuthToken | undefined) => Promise<OAuthToken>) | undefined {
  return (token: OAuthToken | undefined) => {
    const manager = oAuth2Sandbox();
    if (manager === undefined) {
      throw Error('Unable to find the OAuthManager instance');
    }
    if (defaultProvider === undefined) {
      return manager.updateToken(token);
    }
    return defaultProvider(token, manager);
  };
}

function oAuth2ProductionTokenProvider(
  oAuth2Production: () => OAuth2ProductionManager | undefined,
  defaultProvider:
    | ((
        lastOAuthToken: OAuthToken | undefined,
        authManager: OAuth2ProductionManager
      ) => Promise<OAuthToken>)
    | undefined
): ((token: OAuthToken | undefined) => Promise<OAuthToken>) | undefined {
  return (token: OAuthToken | undefined) => {
    const manager = oAuth2Production();
    if (manager === undefined) {
      throw Error('Unable to find the OAuthManager instance');
    }
    if (defaultProvider === undefined) {
      return manager.updateToken(token);
    }
    return defaultProvider(token, manager);
  };
}
