/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { createAuthProviderFromConfig } from './authProvider.js';
import { OAuth2ProductionManager } from './oAuth2ProductionManager.js';
import { OAuth2SandboxManager } from './oAuth2SandboxManager.js';
import {
  AuthParams,
  ClientInterface,
  SdkRequestBuilder,
  SdkRequestBuilderFactory,
  Server,
} from './clientInterface.js';
import { Configuration, Environment } from './configuration.js';
import {
  DEFAULT_CONFIGURATION,
  DEFAULT_RETRY_CONFIG,
} from './defaultConfiguration.js';
import { ApiError } from './core.js';
import {
  AbortError,
  AuthenticatorInterface,
  createRequestBuilderFactory,
  HttpClientInterface,
  RetryConfiguration,
} from './core.js';
import { HttpClient } from './clientAdapter.js';

const USER_AGENT = 'APIMATIC 3.0';

export class Client implements ClientInterface {
  private _config: Readonly<Configuration>;
  private _timeout: number;
  private _retryConfig: RetryConfiguration;
  private _requestBuilderFactory: SdkRequestBuilderFactory;
  public oAuth2SandboxManager?: OAuth2SandboxManager;
  public oAuth2ProductionManager?: OAuth2ProductionManager;

  constructor(config?: Partial<Configuration>) {
    this._config = {
      ...DEFAULT_CONFIGURATION,
      ...config,
    };
    this._retryConfig = {
      ...DEFAULT_RETRY_CONFIG,
      ...this._config.httpClientOptions?.retryConfig,
    };
    this._timeout =
      typeof this._config.httpClientOptions?.timeout != 'undefined'
        ? this._config.httpClientOptions.timeout
        : this._config.timeout;
    this._requestBuilderFactory = createRequestHandlerFactory(
      (server) => getBaseUri(server, this._config),
      createAuthProviderFromConfig(
        this._config,
        () => this.oAuth2SandboxManager,
        () => this.oAuth2ProductionManager
      ),
      new HttpClient(AbortError, {
        timeout: this._timeout,
        clientConfigOverrides: this._config.unstable_httpClientOptions,
        httpAgent: this._config.httpClientOptions?.httpAgent,
        httpsAgent: this._config.httpClientOptions?.httpsAgent,
        proxySettings: this._config.httpClientOptions?.proxySettings,
      }),
      [withErrorHandlers, withUserAgent, withAuthenticationByDefault],
      this._retryConfig
    );
    if (this._config.oAuth2SandboxCredentials) {
      this.oAuth2SandboxManager = new OAuth2SandboxManager(
        this._config.oAuth2SandboxCredentials,
        this
      );
    }
    if (this._config.oAuth2ProductionCredentials) {
      this.oAuth2ProductionManager = new OAuth2ProductionManager(
        this._config.oAuth2ProductionCredentials,
        this
      );
    }
  }

  public getRequestBuilderFactory(): SdkRequestBuilderFactory {
    return this._requestBuilderFactory;
  }

  /**
   * Clone this client and override given configuration options
   */
  public withConfiguration(config: Partial<Configuration>) {
    return new Client({ ...this._config, ...config });
  }
}

function createHttpClientAdapter(client: HttpClient): HttpClientInterface {
  return async (request, requestOptions) => {
    return await client.executeRequest(request, requestOptions);
  };
}

function getBaseUri(server: Server = 'default', config: Configuration): string {
  if (config.environment === Environment.Production) {
    if (server === 'default') {
      return 'https://web-api-v3.sandbox.splitit.com/';
    }
    if (server === 'access token server') {
      return 'https://id.sandbox.splitit.com/connect';
    }
    if (server === 'access token server1') {
      return 'https://id.splitit.com/connect';
    }
  }
  if (config.environment === Environment.Environment2) {
    if (server === 'default') {
      return 'https://web-api-v3.splitit.com/';
    }
    if (server === 'access token server') {
      return 'https://id.sandbox.splitit.com/connect';
    }
    if (server === 'access token server1') {
      return 'https://id.splitit.com/connect';
    }
  }
  throw new Error('Could not get Base URL. Invalid environment or server.');
}

function createRequestHandlerFactory(
  baseUrlProvider: (server?: Server) => string,
  authProvider: AuthenticatorInterface<AuthParams>,
  httpClient: HttpClient,
  addons: ((rb: SdkRequestBuilder) => void)[],
  retryConfig: RetryConfiguration
): SdkRequestBuilderFactory {
  const requestBuilderFactory = createRequestBuilderFactory(
    createHttpClientAdapter(httpClient),
    baseUrlProvider,
    ApiError,
    authProvider,
    retryConfig
  );

  return tap(requestBuilderFactory, ...addons);
}

function tap(
  requestBuilderFactory: SdkRequestBuilderFactory,
  ...callback: ((requestBuilder: SdkRequestBuilder) => void)[]
): SdkRequestBuilderFactory {
  return (...args) => {
    const requestBuilder = requestBuilderFactory(...args);
    callback.forEach((c) => c(requestBuilder));
    return requestBuilder;
  };
}

function withErrorHandlers(rb: SdkRequestBuilder) {
  rb.defaultToError(ApiError);
}

function withUserAgent(rb: SdkRequestBuilder) {
  rb.header('user-agent', USER_AGENT);
}

function withAuthenticationByDefault(rb: SdkRequestBuilder) {
  rb.authenticate([{ oAuth2Sandbox: true }, { oAuth2Production: true }]);
}
