/**
 * splitit-web-api-v3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { HttpClientOptions } from './clientAdapter.js';
import { OAuthScopeOAuth2ProductionEnum } from './models/oAuthScopeOAuth2ProductionEnum.js';
import { OAuthScopeOAuth2SandboxEnum } from './models/oAuthScopeOAuth2SandboxEnum.js';
import { OAuthToken } from './models/oAuthToken.js';
import { OAuth2ProductionManager } from './oAuth2ProductionManager.js';
import { OAuth2SandboxManager } from './oAuth2SandboxManager.js';

/** An interface for all configuration parameters required by the SDK. */
export interface Configuration {
  timeout: number;
  environment: Environment;
  oAuth2SandboxCredentials?: {
    oAuthClientId: string;
    oAuthClientSecret: string;
    oAuthToken?: OAuthToken;
    oAuthScopes?: OAuthScopeOAuth2SandboxEnum[];
    oAuthTokenProvider?: (
      lastOAuthToken: OAuthToken | undefined,
      authManager: OAuth2SandboxManager
    ) => Promise<OAuthToken>;
    oAuthOnTokenUpdate?: (token: OAuthToken) => void;
    oAuthClockSkew?: number;
  };
  oAuth2ProductionCredentials?: {
    oAuthClientId: string;
    oAuthClientSecret: string;
    oAuthToken?: OAuthToken;
    oAuthScopes?: OAuthScopeOAuth2ProductionEnum[];
    oAuthTokenProvider?: (
      lastOAuthToken: OAuthToken | undefined,
      authManager: OAuth2ProductionManager
    ) => Promise<OAuthToken>;
    oAuthOnTokenUpdate?: (token: OAuthToken) => void;
    oAuthClockSkew?: number;
  };
  httpClientOptions?: Partial<HttpClientOptions>;
  unstable_httpClientOptions?: any;
}

/** Environments available for API */
export enum Environment {
  Production = 'production',
  Environment2 = 'environment2',
}
